// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq9iTbS2eURSePENB0wpzCpysyLNgv3Ls',
    appId: '1:192824470633:web:ec0cc3ad013e0439e9c6f8',
    messagingSenderId: '192824470633',
    projectId: 'academic-atlas-491309-s4',
    authDomain: 'academic-atlas-491309-s4.firebaseapp.com',
    storageBucket: 'academic-atlas-491309-s4.appspot.com',
    measurementId: 'G-XZT1BZPJR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXqC2vhk8pRZAn1S0spujqJxU56xywL2c',
    appId: '1:192824470633:android:229a1dd1a4c413cbe9c6f8',
    messagingSenderId: '192824470633',
    projectId: 'academic-atlas-491309-s4',
    storageBucket: 'academic-atlas-491309-s4.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC4pQCOxrVx6Q8EhrhhtssMF7C8rqEC8s',
    appId: '1:192824470633:ios:abd1b43c8c426707e9c6f8',
    messagingSenderId: '192824470633',
    projectId: 'academic-atlas-491309-s4',
    storageBucket: 'academic-atlas-491309-s4.appspot.com',
    iosBundleId: 'com.example.agroMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC4pQCOxrVx6Q8EhrhhtssMF7C8rqEC8s',
    appId: '1:192824470633:ios:abd1b43c8c426707e9c6f8',
    messagingSenderId: '192824470633',
    projectId: 'academic-atlas-491309-s4',
    storageBucket: 'academic-atlas-491309-s4.appspot.com',
    iosBundleId: 'com.example.agroMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq9iTbS2eURSePENB0wpzCpysyLNgv3Ls',
    appId: '1:192824470633:web:31058af78b874847e9c6f8',
    messagingSenderId: '192824470633',
    projectId: 'academic-atlas-491309-s4',
    authDomain: 'academic-atlas-491309-s4.firebaseapp.com',
    storageBucket: 'academic-atlas-491309-s4.appspot.com',
    measurementId: 'G-EDN5GD9M17',
  );
}
